server.port=8081

spring.application.name=internship-app-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/internship_app
spring.datasource.username=internship_user
spring.datasource.password=internship_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/internship-app
