package com.example.internshipapp.common.enums;

public enum ExpenseType {
    MATERIAL_PURCHASE,
    MATERIAL_TRANSPORT,
    EQUIPMENT_FUEL,
    EQUIPMENT_MAINTENANCE,
    EQUIPMENT_TRANSPORT,
    EQUIPMENT_EXTERNAL_RENTAL,
    EMPLOYEE_DAILY_EXPENSES,
    EMPLOYEE_SALARY_ADVANCE,
    COMPANY_STAFF_DAILY_EXPENSES,
    SUBCONTRACTING_SERVICE,
    SITE_EXPENSE,
    GENERAL_EXPENSE,
    OTHER_EXPENSE
}
